# Base: localhost:5001/apm-repo/demo/node:20-alpine
FROM localhost:5001/apm-repo/demo/node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3000

CMD ["node", "server.js"]
