# =============================================================================
# PRODUCTION STACK — Monitoring & Observability
# Services: Prometheus, Grafana, Loki, Promtail, Jaeger, Splunk
# Usage: docker compose -f monitoring.yml up -d
# =============================================================================

services:

  # ---------------------------------------------------------------------------
  # Prometheus — Metrics collection and alerting
  # ---------------------------------------------------------------------------
  prod-prometheus:
    image: prom/prometheus:latest
    container_name: prod-prometheus
    restart: unless-stopped
    ports:
      - "${PROD_PROMETHEUS_PORT:-19090}:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prod-prometheus-data:/prometheus
    networks:
      - prod-platform-net

  # ---------------------------------------------------------------------------
  # Grafana — Dashboards and visualization
  # ---------------------------------------------------------------------------
  prod-grafana:
    image: grafana/grafana:latest
    container_name: prod-grafana
    restart: unless-stopped
    ports:
      - "${PROD_GRAFANA_PORT:-13000}:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${PROD_GRAFANA_ADMIN_PASSWORD:-admin123}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: http://localhost:${PROD_GRAFANA_PORT:-13000}
    volumes:
      - prod-grafana-data:/var/lib/grafana
    depends_on:
      - prod-prometheus
      - prod-loki
    networks:
      - prod-platform-net

  # ---------------------------------------------------------------------------
  # Loki — Log aggregation backend
  # ---------------------------------------------------------------------------
  prod-loki:
    image: grafana/loki:latest
    container_name: prod-loki
    restart: unless-stopped
    ports:
      - "${PROD_LOKI_PORT:-13100}:3100"
    volumes:
      - ./config/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - prod-loki-data:/loki
    networks:
      - prod-platform-net

  # ---------------------------------------------------------------------------
  # Promtail — Log collector (ships container logs to Loki)
  # ---------------------------------------------------------------------------
  prod-promtail:
    image: grafana/promtail:latest
    container_name: prod-promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./config/promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    depends_on:
      - prod-loki
    networks:
      - prod-platform-net

  # ---------------------------------------------------------------------------
  # Jaeger — Distributed tracing
  # ---------------------------------------------------------------------------
  prod-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: prod-jaeger
    restart: unless-stopped
    ports:
      - "${PROD_JAEGER_UI_PORT:-26686}:16686"
      - "${PROD_JAEGER_OTLP_GRPC_PORT:-14317}:4317"
      - "${PROD_JAEGER_OTLP_HTTP_PORT:-14318}:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    networks:
      - prod-platform-net

  # ---------------------------------------------------------------------------
  # Splunk — Event logging and SIEM
  # ---------------------------------------------------------------------------
  prod-splunk:
    image: splunk/splunk:latest
    container_name: prod-splunk
    restart: unless-stopped
    ports:
      - "${PROD_SPLUNK_HEC_PORT:-18088}:8088"
      - "${PROD_SPLUNK_UI_PORT:-20000}:8000"
    environment:
      SPLUNK_PASSWORD: ${PROD_SPLUNK_PASSWORD:-Admin@1234}
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_START_ARGS: --accept-license
    volumes:
      - prod-splunk-etc:/opt/splunk/etc
      - prod-splunk-var:/opt/splunk/var
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - prod-platform-net

volumes:
  prod-prometheus-data:
    name: prod-prometheus-data
  prod-grafana-data:
    name: prod-grafana-data
  prod-loki-data:
    name: prod-loki-data
  prod-splunk-etc:
    name: prod-splunk-etc
  prod-splunk-var:
    name: prod-splunk-var

networks:
  prod-platform-net:
    name: prod-platform-net
    driver: bridge
