apiVersion: v1
kind: Namespace
metadata:
  name: etcd-cluster
  labels:
    app: etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: etcd-cluster
  labels:
    app: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.16
          command:
            - etcd
            - --name=etcd0
            - --data-dir=/etcd-data
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://0.0.0.0:2379
            - --listen-peer-urls=http://0.0.0.0:2380
            - --initial-advertise-peer-urls=http://0.0.0.0:2380
            - --initial-cluster=etcd0=http://0.0.0.0:2380
            - --initial-cluster-token=etcd-cluster-token
            - --initial-cluster-state=new
          ports:
            - containerPort: 2379
              protocol: TCP
              name: client
            - containerPort: 2380
              protocol: TCP
              name: peer
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: etcd-cluster
  labels:
    app: etcd
spec:
  type: NodePort
  selector:
    app: etcd
  ports:
    - port: 2379
      targetPort: 2379
      nodePort: 30409
      protocol: TCP
      name: client
