apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
  labels:
    app: forgejo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:9
          ports:
            - containerPort: 3000
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "25m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app: forgejo
spec:
  type: NodePort
  selector:
    app: forgejo
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30204
      protocol: TCP
