apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  labels:
    app: linkerd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-web
  namespace: linkerd
  labels:
    app: linkerd-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkerd-web
  template:
    metadata:
      labels:
        app: linkerd-web
    spec:
      containers:
        - name: linkerd-web
          image: cr.l5d.io/linkerd/web:edge-24.12.2
          ports:
            - containerPort: 8084
              protocol: TCP
          env:
            - name: LINKERD_NAMESPACE
              value: "linkerd"
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-web
  namespace: linkerd
  labels:
    app: linkerd-web
spec:
  type: NodePort
  selector:
    app: linkerd-web
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30316
      protocol: TCP
