apiVersion: v1
kind: Namespace
metadata:
  name: onedev
  labels:
    app: onedev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onedev
  namespace: onedev
  labels:
    app: onedev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onedev
  template:
    metadata:
      labels:
        app: onedev
    spec:
      containers:
        - name: onedev
          image: 1dev/server:latest
          ports:
            - containerPort: 6610
          volumeMounts:
            - name: data
              mountPath: /opt/onedev
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: onedev
  namespace: onedev
  labels:
    app: onedev
spec:
  type: NodePort
  selector:
    app: onedev
  ports:
    - port: 6610
      targetPort: 6610
      nodePort: 30205
      protocol: TCP
