log:
  level: info

runner:
  file: /data/.runner
  capacity: 6
  envs:
    NEXUS_REGISTRY: "localhost:5001"
    NEXUS_INTERNAL_REGISTRY: "ai-nexus:5001"
    SONARQUBE_URL: "http://ai-sonarqube:9000"
    SPLUNK_HEC_URL: "http://ai-splunk:8088"
    DEVOPS_BACKEND_URL: "http://devops-tools-backend:8003"
  timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  labels:
    - "self-hosted"
    - "docker"
    - "linux"
    - "x64"

cache:
  enabled: true
  dir: /data/cache
  host: ""
  port: 0
  external_server: ""

container:
  network: "global-infra-net"
  privileged: true
  options: ""
  workdir_parent: /workspace
  valid_volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  docker_host: ""
  force_pull: false

host:
  workdir_parent: /data/workspace
